---
- name: Install packages
  apt: 
    name: ['htop', 'golang', 'openjdk-8-jre-headless']
    state: present

- name: Install lastpass
  apt: 
    name: [ 'bash-completion', 'build-essential', 'cmake', 'libcurl3-openssl-dev', 'libssl-dev', 'libxml2', 'libxml2-dev', 'pkg-config', 'ca-certificates', 'xclip']       
    state: present

      